services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - 5455:5432
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: [CMD-SHELL, pg_isready -d next_todo -U postgres]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  app_network:
    external: true
